/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/managed/consumer-env.d.ts -c managed/consumer.json --env-interface ManagedConsumerEnv --include-runtime false` (hash: 92634ca7899cae972d2ec972d344c8cc)
interface __BaseEnv_ManagedConsumerEnv {
  MANAGED_STAGE: 'local-scaffold';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./consumer');
  }
  interface Env extends __BaseEnv_ManagedConsumerEnv {}
}
interface ManagedConsumerEnv extends __BaseEnv_ManagedConsumerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'MANAGED_STAGE'>> {}
}

export { ManagedConsumerEnv };
