/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/managed/local/delivery-env.d.ts -c managed/local/delivery.json --env-interface LocalDeliveryEnv --include-runtime false` (hash: 664828bfc512097db4f06d03087c6e49)
interface __BaseEnv_LocalDeliveryEnv {
  LOCAL_RECEIPTS: DurableObjectNamespace<import('./delivery').LocalManagedReceipt>;
  LOCAL_AUTHORITY: Fetcher /* bugdrop-managed-harness-authority */;
  LOCAL_FAKE_GITHUB: Fetcher /* bugdrop-managed-harness-fake-github */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./delivery');
    durableNamespaces: 'LocalManagedReceipt';
  }
  interface Env extends __BaseEnv_LocalDeliveryEnv {}
}
interface LocalDeliveryEnv extends __BaseEnv_LocalDeliveryEnv {}

export { LocalDeliveryEnv };
