/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/managed/local/ingress-env.d.ts -c managed/local/ingress.json --env-interface LocalIngressEnv --include-runtime false` (hash: 6f1d2e97d16498ad779cf7c6065addf8)
interface __BaseEnv_LocalIngressEnv {
  LOCAL_AUTHORITY: Fetcher /* bugdrop-managed-harness-authority */;
  LOCAL_DELIVERY: Fetcher /* bugdrop-managed-harness-delivery */;
  LOCAL_EVIDENCE: Fetcher /* bugdrop-managed-harness-evidence */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./ingress');
  }
  interface Env extends __BaseEnv_LocalIngressEnv {}
}
interface LocalIngressEnv extends __BaseEnv_LocalIngressEnv {}

export { LocalIngressEnv };
