/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/managed/staging/github-env.d.ts -c managed/staging/github.json --env staging --strict-vars false --env-interface StagingGithubEnv --include-runtime false` (hash: 586dac40cca11c89bf3c2ef4c32f9fc1)
interface __BaseEnv_StagingGithubEnv {
  ENVIRONMENT: string;
  STAGING_ENABLED: string;
  STAGING_DELIVERY_ENABLED: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./github');
  }
  interface Env extends __BaseEnv_StagingGithubEnv {}
}
interface StagingGithubEnv extends __BaseEnv_StagingGithubEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'ENVIRONMENT' | 'STAGING_ENABLED' | 'STAGING_DELIVERY_ENABLED'>
  > {}
}

export { StagingGithubEnv };
