/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/managed/staging/ingress-env.d.ts -c managed/staging/ingress.json --env staging --strict-vars false --env-interface StagingIngressEnv --include-runtime false` (hash: e17ed9e22668204951059151293f4dae)
interface __BaseEnv_StagingIngressEnv {
  ENVIRONMENT: string;
  STAGING_ENABLED: string;
  STAGING_AUTHORITY: Service /* entrypoint IssuerAuthority from bugdrop-managed-authority-staging */;
  STAGING_DELIVERY: Service /* entrypoint StagingDelivery from bugdrop-managed-delivery-staging */;
  STAGING_GITHUB_WEBHOOK: Service /* entrypoint GithubWebhook from bugdrop-managed-github-staging */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./ingress');
  }
  interface Env extends __BaseEnv_StagingIngressEnv {}
}
interface StagingIngressEnv extends __BaseEnv_StagingIngressEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'ENVIRONMENT' | 'STAGING_ENABLED'>
  > {}
}

export { StagingIngressEnv };
